name: MyTest 

defaults:
  run:
    shell: bash

on:  # Runs on all push events 
  push:

jobs:
  call-test-workflow:
    uses: pylhc/.github/.github/workflows/echo_test.yml@reusable_workflows
    with:
      test-input: "Hello World / "